# Generated by Django 5.1.6 on 2025-02-27 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0006_datamanagementplan_data_management'),
        ('xref', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crossreference',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controls', to='compliances.domain'),
        ),
    ]
