# Generated by Django 3.1.7 on 2023-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xref', '0002_auto_20230624_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('approved', 'Approved')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('approved', 'Approved')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='statement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('approved', 'Approved')], default='draft', max_length=10),
        ),
    ]
