# Generated by Django 5.1.6 on 2025-02-28 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xref', '0002_alter_crossreference_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossreference',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
