# Generated by Django 5.0.7 on 2024-08-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xref', '0003_auto_20230625_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementtosubstatement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
