# Generated by Django 5.1.3 on 2024-12-11 00:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xref', '0004_alter_statementtosubstatement_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substatement',
            name='statements',
        ),
        migrations.RemoveField(
            model_name='substatement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='substatement',
            name='modified_by',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('predicate', models.CharField(max_length=255)),
                ('object', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='TaskStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xref.statement')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xref.task')),
            ],
            options={
                'ordering': ('index',),
                'unique_together': {('statement', 'task')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='statements',
            field=models.ManyToManyField(related_name='tasks', through='xref.TaskStatement', to='xref.statement'),
        ),
        migrations.DeleteModel(
            name='StatementToSubstatement',
        ),
        migrations.DeleteModel(
            name='Substatement',
        ),
    ]
