# Generated by Django 5.1.6 on 2025-02-28 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0006_datamanagementplan_data_management'),
        ('xref', '0004_remove_crossreference_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='crossreference',
            name='domain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cross_reference', to='compliances.domain'),
        ),
    ]
