# Generated by Django 5.1.6 on 2025-02-19 11:46

import projects.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'backlog',
                'verbose_name_plural': 'backlogs',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('index', models.SmallIntegerField(db_index=True, default=1000)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('number', models.PositiveSmallIntegerField(db_index=True, default=projects.models.get_next_task_number, editable=False)),
            ],
            options={
                'verbose_name': 'epic',
                'verbose_name_plural': 'epics',
                'ordering': ['index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('prefix', models.CharField(blank=True, default='ISO27K', max_length=255, null=True)),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('start_date', models.DateField(blank=True, default='2025-01-01', null=True)),
                ('sprint_length_in_days', models.PositiveSmallIntegerField(default=21)),
                ('release_length_in_days', models.PositiveSmallIntegerField(default=21)),
                ('epics_per_release', models.PositiveSmallIntegerField(default=2)),
                ('story_points_in_sprint', models.PositiveSmallIntegerField(default=10)),
                ('ideal_story_points_per_day', models.PositiveSmallIntegerField(default=10, help_text='Accross all teams. Used to estimate the project cmpletion date, for example in the burndown chart.')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('index', models.SmallIntegerField(db_index=True, default=1000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='new', max_length=32)),
            ],
            options={
                'verbose_name': 'release',
                'verbose_name_plural': 'releases',
                'ordering': ['index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
            ],
            options={
                'verbose_name': 'roadmap',
                'verbose_name_plural': 'roadmaps',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('index', models.SmallIntegerField(db_index=True, default=1000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='new', max_length=32)),
            ],
            options={
                'verbose_name': 'sprint',
                'verbose_name_plural': 'sprints',
                'ordering': ['index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('index', models.SmallIntegerField(db_index=True, default=1000)),
                ('slug', models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='new', max_length=32)),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'ordering': ['index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('index', models.SmallIntegerField(db_index=True, default=1000)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('number', models.PositiveSmallIntegerField(db_index=True, default=projects.models.get_next_task_number, editable=False)),
                ('story_points', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='new', max_length=32)),
                ('priority', models.CharField(choices=[('blocker', 'Blocker'), ('very-high', 'Very high'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('very-low', 'Very low'), ('trivial', 'Trivial')], default='medium', max_length=32)),
            ],
            options={
                'verbose_name': 'story',
                'verbose_name_plural': 'stories',
                'ordering': ['index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
