# Generated by Django 5.1.4 on 2024-12-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='epics_per_release',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='project',
            name='release_length_in_days',
            field=models.PositiveSmallIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='project',
            name='sprint_length_in_days',
            field=models.PositiveSmallIntegerField(default=21),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='storypoints_per_sprint',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
