# Generated by Django 5.1.4 on 2025-01-12 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='storypoints_in_sprint',
            new_name='story_points_in_sprint',
        ),
    ]
