# Generated by Django 5.1.4 on 2025-01-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='new', max_length=32),
        ),
    ]
