# Generated by Django 5.1.4 on 2025-01-07 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('workflows', '0071_remove_trainingattended_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='status',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('index', models.SmallIntegerField(db_index=True, default=1000)),
                ('slug', models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='new', max_length=32)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='projects.sprint')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
            ],
            options={
                'verbose_name': 'list',
                'verbose_name_plural': 'lists',
                'ordering': ['index'],
                'abstract': False,
            },
        ),
    ]
