# Generated by Django 5.1.4 on 2025-01-06 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('ongoing', 'Ongoing'), ('closed', 'Closed')], default='new', max_length=32),
        ),
    ]
