# Generated by Django 5.1.4 on 2025-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
