# Generated by Django 5.1.4 on 2025-01-14 21:18

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='number',
            field=models.PositiveSmallIntegerField(db_index=True, default=projects.models.get_next_task_number, editable=False),
        ),
        migrations.AddField(
            model_name='story',
            name='number',
            field=models.PositiveSmallIntegerField(db_index=True, default=projects.models.get_next_task_number, editable=False),
        ),
    ]
