# Generated by Django 5.1.4 on 2025-01-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_sprint_status_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.status'),
        ),
    ]
