# Generated by Django 5.1.4 on 2025-01-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0003_alter_category_team_delete_team'),
        ('projects', '0002_remove_projectteam_compliance_team_projectteam_name_and_more'),
        ('workflows', '0071_remove_trainingattended_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTeam',
            new_name='Team',
        ),
        migrations.AlterField(
            model_name='project',
            name='prefix',
            field=models.CharField(blank=True, default='ISO27K', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, default='2025-01-01', null=True),
        ),
    ]
