# Generated by Django 5.1.4 on 2025-01-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_story_story_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ideal_story_points_per_day',
            field=models.PositiveSmallIntegerField(default=10, help_text='Accross all teams. Used to estimate the project cmpletion date, for example in the burndown chart.'),
        ),
    ]
