# Generated by Django 5.1.4 on 2025-01-07 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_story_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='active_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.sprint'),
        ),
    ]
