# Generated by Django 5.1.4 on 2025-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_epic_number_story_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='priority',
            field=models.CharField(choices=[('blocker', 'Blocker'), ('very-high', 'Very high'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('very-low', 'Very low'), ('trivial', 'Trivial')], default='medium', max_length=32),
        ),
    ]
