# Generated by Django 5.1.4 on 2025-01-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_sprint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.sprint'),
        ),
    ]
