# Generated by Django 5.1.4 on 2025-01-09 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0002_initial'),
        ('projects', '0007_project_current_sprint'),
        ('workflows', '0071_remove_trainingattended_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_sprint',
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('compliance_team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='project_teams', to='compliances.team')),
                ('current_sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='projects.sprint')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
