# Generated by Django 5.1.4 on 2025-01-09 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_current_sprint_projectteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.projectteam'),
        ),
        migrations.AlterField(
            model_name='story',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.projectteam'),
        ),
    ]
