services :
  usm:
    build: 
      context: .
      dockerfile: dev/Dockerfile.dev
    command: /src/deploy/docker-entrypoint.sh
    ports:
      - "8030:8000"
      - "6930:6900"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./:/src
    environment:
      - DJANGO_DEBUG=True
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db
      - REDIS_URL="redis://tanssikalenteri-redis:6379/0"
