# fly.toml app configuration file generated for usm on 2024-08-02T08:21:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'usm'
primary_region = 'arn'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  PORT = '8000'
  EMAIL_HOST='smtp.eu.mailgun.org'
  EMAIL_HOST_USER='postmaster@mg.usm.coach'
  ALLOWED_HOSTS = ['usm.fly.dev', 'usm.tools']
  CSRF_TRUSTED_ORIGINS = ['usm.fly.dev', 'usm.tools']

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
