# Generated by Django 5.1.6 on 2025-02-19 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'default_related_name': 'instructions', 'ordering': ['modified_at'], 'verbose_name': 'instruction', 'verbose_name_plural': 'instructions'},
        ),
        migrations.AlterField(
            model_name='instruction',
            name='responsible',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflows.responsibility'),
        ),
    ]
