# Generated by Django 5.1.6 on 2025-02-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
    ]
