# Generated by Django 5.1.6 on 2025-02-26 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('workflows', '0002_profile_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'default_related_name': 'actions', 'ordering': ['index'], 'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'default_related_name': 'activities', 'ordering': ('index',), 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='instruction',
            options={'default_related_name': 'instructions', 'ordering': ['modified_at'], 'verbose_name': 'Instruction', 'verbose_name_plural': 'Instructions'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'default_related_name': 'profiles', 'ordering': ('index',), 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='responsibility',
            options={'default_related_name': 'responsibilities', 'ordering': ['index'], 'verbose_name': 'Responsibility', 'verbose_name_plural': 'Responsibilities'},
        ),
        migrations.AlterModelOptions(
            name='routine',
            options={'default_related_name': 'routines', 'ordering': ('index',), 'verbose_name': 'Routine', 'verbose_name_plural': 'Routines'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'default_related_name': 'shares', 'verbose_name': 'Share', 'verbose_name_plural': 'Shares'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'default_related_name': 'steps', 'ordering': ('index',), 'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_related_name': 'tasks', 'ordering': ('index',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=10, verbose_name='Customer type'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_require_tag',
            field=models.ForeignKey(help_text='Require that action has this label', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taggit.tag', verbose_name='Label required from action'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='routine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workflows.routine', verbose_name='Routine'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
