# Generated by Django 5.1.4 on 2025-01-26 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_responsible_description_responsible_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('types', models.CharField(blank=True, default='', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.activity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.organizationunit')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.profile')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
            ],
            options={
                'verbose_name': 'responsible',
                'verbose_name_plural': 'responsibles',
                'ordering': ['modified_at'],
                'default_related_name': 'responsibles',
            },
        ),
        migrations.AlterField(
            model_name='workinstruction',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.action'),
        ),
        migrations.DeleteModel(
            name='Responsible',
        ),
    ]
