# Generated by Django 5.1.6 on 2025-02-19 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_alter_instruction_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='responsible',
        ),
        migrations.AddField(
            model_name='instruction',
            name='responsibility',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruction', to='workflows.responsibility'),
        ),
    ]
