# Generated by Django 3.1.7 on 2022-05-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_workflow_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ('index',)},
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
