# Generated by Django 5.1.4 on 2025-01-26 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_action_alter_workinstruction_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='skipped',
            field=models.BooleanField(default=False, help_text='This activity is skipped'),
        ),
        migrations.AddField(
            model_name='step',
            name='skipped',
            field=models.BooleanField(default=False, help_text='This step is skipped'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflows.step'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflows.routine'),
        ),
    ]
