# Generated by Django 5.1.6 on 2025-03-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_action_options_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('nl', 'Dutch')], default='en', error_messages={'invalid_choice': 'Wrong language choice', 'required': 'You must choose a language'}, max_length=2, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('nl', 'Dutch')], default='fi', error_messages={'invalid_choice': 'Wrong language choice', 'required': 'You must choose the language'}, max_length=2, verbose_name='Language'),
        ),
    ]
