# Generated by Django 5.1.6 on 2025-02-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_remove_instruction_responsible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='responsibility',
        ),
    ]
