# Generated by Django 3.1.7 on 2022-05-31 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_auto_20220530_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='context',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workflows.context'),
            preserve_default=False,
        ),
    ]
