# Generated by Django 5.1.6 on 2025-02-09 04:56

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_task'),
    ]

    operations = [
        TrigramExtension(),
    ]
