# Generated by Django 3.1.7 on 2022-05-31 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_profile_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='workflows.context'),
        ),
    ]
