# Generated by Django 5.1.6 on 2025-02-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_trigram_ext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='actions',
        ),
    ]
