# Generated by Django 3.1.7 on 2022-06-01 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_auto_20220531_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='fork',
            field=models.ForeignKey(help_text='Only used in template workflows o specify forks to sub-workflow. In real workflows, all the forks have been expanded into one single workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='workflows.context'),
        ),
    ]
