# Generated by Django 5.1.6 on 2025-02-19 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('workflows', '0007_action_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='action_require_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taggit.tag'),
        ),
        migrations.AddField(
            model_name='task',
            name='routine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workflows.routine'),
        ),
    ]
