# Generated by Django 3.1.7 on 2022-06-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_auto_20220601_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='process_depth',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Used in actualized workflows, to signal how many levels of sub-processes there are', null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='fork',
            field=models.ForeignKey(help_text='Only used in template workflows o specify forks to sub-workflow. In actualized workflows, all the forks have been expanded into one single workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow'),
        ),
    ]
