# Generated by Django 5.1.6 on 2025-02-18 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_remove_task_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.task'),
        ),
    ]
