# Generated by Django 5.1.6 on 2025-02-18 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_action_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.profile'),
        ),
    ]
