# Generated by Django 5.1.6 on 2025-02-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_task_action_require_tag_task_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_customers', to='workflows.customer'),
        ),
        migrations.AlterField(
            model_name='servicecustomer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_customers', to='workflows.service'),
        ),
    ]
