# Generated by Django 5.1.6 on 2025-02-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_alter_action_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Responsibility',
        ),
    ]
