# Generated by Django 5.1.6 on 2025-02-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_alter_servicecustomer_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workflows.organizationunit'),
        ),
    ]
