# Generated by Django 3.1.7 on 2022-06-07 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0009_auto_20220601_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='context',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='organizationunit',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='responsible',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='context',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contexts_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='responsible',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibles_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='step',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='context',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contexts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsibles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='step',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
