# Generated by Django 3.1.7 on 2022-06-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_auto_20220607_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='index',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
