# Generated by Django 5.1.6 on 2025-02-18 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0010_rename_action_responsibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibility',
            options={'default_related_name': 'responsibilities', 'ordering': ['index'], 'verbose_name': 'responsibilities', 'verbose_name_plural': 'responsibilities'},
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='description',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='organization_unit',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='task',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='title',
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.profile'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.activity')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.task')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
            ],
            options={
                'verbose_name': 'action',
                'verbose_name_plural': 'actions',
                'ordering': ['index'],
                'default_related_name': 'actions',
            },
        ),
        migrations.AddField(
            model_name='responsibility',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.action'),
        ),
    ]
