# Generated by Django 3.1.7 on 2022-06-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0012_workinstruction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Context',
            new_name='Service',
        ),
    ]
