# Generated by Django 3.1.7 on 2022-06-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0015_auto_20220628_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_meta',
            field=models.BooleanField(default=False),
        ),
    ]
