# Generated by Django 3.1.7 on 2022-10-13 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0017_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='fork',
            field=models.ForeignKey(help_text='Only used in template workflows to specify forks to sub-workflow. In actualized workflows, all the forks have been expanded into one single workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow'),
        ),
    ]
