# Generated by Django 3.1.7 on 2022-10-21 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0018_auto_20221013_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationunit',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='organization_units', to='workflows.account'),
            preserve_default=False,
        ),
    ]
