# Generated by Django 3.1.7 on 2022-10-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0021_auto_20221023_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('index',), 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='responsible',
            options={'ordering': ('modified_at',), 'verbose_name_plural': 'Responsibles'},
        ),
        migrations.AlterModelOptions(
            name='workinstruction',
            options={'ordering': ('modified_at',), 'verbose_name_plural': 'Work instructions'},
        ),
    ]
