# Generated by Django 3.1.7 on 2022-10-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0022_auto_20221025_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['index'], 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='responsible',
            options={'ordering': ['modified_at'], 'verbose_name_plural': 'Responsibles'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='workinstruction',
            options={'ordering': ['modified_at'], 'verbose_name_plural': 'Work instructions'},
        ),
    ]
