# Generated by Django 3.1.7 on 2022-10-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0023_auto_20221025_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('can_edit_global_template', 'Can edit the service containing the global workflow templates')]},
        ),
        migrations.AddField(
            model_name='service',
            name='is_global_template',
            field=models.BooleanField(default=False),
        ),
    ]
