# Generated by Django 3.1.7 on 2022-10-26 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0025_auto_20221026_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow'),
        ),
    ]
