# Generated by Django 3.1.7 on 2022-10-26 18:39

from django.db import migrations

def mark_global_template_service(apps, schema_editor):
    Service = apps.get_model('workflows', 'Service')

    service = Service.objects.get(id='69fea6d9-bf2c-4eb6-9605-1a78145b9549')
    service.is_global_template = True
    service.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0026_workflow_based_on'),
    ]

    operations = [
        #migrations.RunPython(mark_global_template_service),
    ]
