# Generated by Django 3.1.7 on 2022-10-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0027_auto_20221026_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('index',), 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'ordering': ('index',)},
        ),
        migrations.AddField(
            model_name='responsible',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
    ]
