# Generated by Django 3.1.7 on 2022-11-03 01:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0028_auto_20221026_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scope', models.CharField(choices=[('workflow', 'Workflow')], default='workflow', max_length=10)),
                ('token1', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('token2', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='workflows.workflow')),
            ],
        ),
    ]
