# Generated by Django 3.1.7 on 2022-11-03 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0029_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='share',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='share',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='share',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='workflows.service'),
        ),
    ]
