# Generated by Django 3.1.7 on 2022-11-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0030_auto_20221103_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='last_access',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
