# Generated by Django 3.1.7 on 2022-11-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0035_auto_20221110_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='service',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='service',
        ),
        migrations.RemoveField(
            model_name='share',
            name='service',
        ),
    ]
