# Generated by Django 3.1.7 on 2022-11-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0036_auto_20221110_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'ordering': ('index',)},
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='level',
            field=models.PositiveSmallIntegerField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='level',
            field=models.PositiveSmallIntegerField(db_index=True, default=None, editable=False, null=True),
        ),
    ]
