# Generated by Django 3.1.7 on 2022-11-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0037_auto_20221113_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('index',), 'permissions': [('can_edit_global_template', 'Can edit the service containing the global workflow templates')]},
        ),
    ]
