# Generated by Django 3.1.7 on 2022-12-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0038_auto_20221113_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='organization',
            new_name='providing_organization',
        ),
    ]
