# Generated by Django 3.1.7 on 2022-12-07 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0040_servicecustomer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationunit',
            old_name='parent',
            new_name='old_parent',
        ),
    ]
