# Generated by Django 3.1.7 on 2022-12-07 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0041_auto_20221207_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='parent',
            new_name='old_parent',
        ),
    ]
