# Generated by Django 3.1.7 on 2022-12-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0042_auto_20221207_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationunit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'permissions': [('can_edit_global_template', 'Can edit the service containing the global workflow templates')]},
        ),
        migrations.RemoveField(
            model_name='organizationunit',
            name='index',
        ),
        migrations.RemoveField(
            model_name='organizationunit',
            name='level',
        ),
        migrations.RemoveField(
            model_name='service',
            name='index',
        ),
        migrations.RemoveField(
            model_name='service',
            name='level',
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='old_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_children', to='workflows.organizationunit'),
        ),
        migrations.AlterField(
            model_name='service',
            name='old_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_children', to='workflows.service'),
        ),
    ]
