# Generated by Django 3.1.7 on 2022-12-07 06:02

from django.db import migrations, connection

class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0043_auto_20221207_0601'),
    ]

    is_postgres = connection.vendor == "postgres"
    operations = [
        migrations.RunSQL(
            'ALTER INDEX workflows_organizationunit_parent_id_3fe1089d rename TO workflows_organizationunit_old_parent_id_3fe1089d',
        ),
        migrations.RunSQL(
            'ALTER INDEX workflows_service_parent_id_049871f4 rename TO workflows_service_old_parent_id_049871f4≈',
        ),
    ]
