# Generated by Django 3.1.7 on 2022-12-07 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0044_auto_20221207_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workflows.organizationunit', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workflows.service', verbose_name='parent'),
        ),
    ]
