# Generated by Django 3.1.7 on 2022-12-07 06:02

from django.db import migrations

def parent_migration(apps, schema_editor):
    Service = apps.get_model('workflows', 'Service')

    for s in Service.objects.all():
        s.parent = s.old_parent
        s.save()

    OrganizationUnit = apps.get_model('workflows', 'OrganizationUnit')

    for ou in OrganizationUnit.objects.all():
        ou.parent = ou.old_parent
        ou.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0045_auto_20221207_0603'),
    ]

    operations = [
        migrations.RunPython(parent_migration),
    ]
