# Generated by Django 3.1.7 on 2022-12-08 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0046_auto_20221207_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.profile'),
        ),
    ]
