# Generated by Django 3.1.7 on 2022-12-08 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0047_auto_20221208_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsible',
            name='organization_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.organizationunit'),
        ),
    ]
