# Generated by Django 3.1.7 on 2022-12-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0048_responsible_organization_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationunit',
            name='owner',
        ),
    ]
