# Generated by Django 3.1.7 on 2022-12-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0049_remove_organizationunit_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'default_related_name': 'activities', 'ordering': ('index',), 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'default_related_name': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'default_related_name': 'organization_units'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'default_related_name': 'profiles'},
        ),
        migrations.AlterModelOptions(
            name='responsible',
            options={'default_related_name': 'responsibles', 'ordering': ['modified_at'], 'verbose_name_plural': 'Responsibles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'default_related_name': 'services', 'permissions': [('can_edit_global_template', 'Can edit the service containing the global workflow templates')]},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'default_related_name': 'shares'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'default_related_name': 'steps', 'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'default_related_name': 'workflows', 'ordering': ('index',)},
        ),
        migrations.AlterModelOptions(
            name='workinstruction',
            options={'default_related_name': 'work_instructions', 'ordering': ['modified_at'], 'verbose_name_plural': 'Work instructions'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_units', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='organization_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='workflows.organizationunit'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='workflows.profile'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibles', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='share',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='step',
            name='fork',
            field=models.ForeignKey(help_text='Only used in template workflows to specify forks to sub-workflow. In actualized workflows, all the forks have been expanded into one single workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='step',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='workinstruction',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_instructions', to='workflows.tenant'),
        ),
    ]
