# Generated by Django 3.1.7 on 2022-12-09 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0050_auto_20221209_2135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecustomer',
            options={'default_related_name': 'service_customers'},
        ),
        migrations.AlterField(
            model_name='servicecustomer',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_customers', to='workflows.tenant'),
        ),
    ]
