# Generated by Django 3.1.7 on 2022-12-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0051_auto_20221209_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationunit',
            name='old_parent',
        ),
    ]
