# Generated by Django 3.1.7 on 2022-12-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0052_remove_organizationunit_old_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='old_parent',
        ),
    ]
