# Generated by Django 3.1.7 on 2022-12-20 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0053_remove_service_old_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='slug',
        ),
    ]
