# Generated by Django 3.1.7 on 2022-12-20 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0054_remove_workflow_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='providing_organization',
        ),
    ]
