# Generated by Django 3.1.7 on 2023-06-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0055_remove_service_providing_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'default_related_name': 'activities', 'ordering': ('index',), 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'default_related_name': 'customers', 'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='organizationunit',
            options={'default_related_name': 'organization_units', 'verbose_name': 'organization unit', 'verbose_name_plural': 'organization units'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'default_related_name': 'profiles', 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AlterModelOptions(
            name='responsible',
            options={'default_related_name': 'responsibles', 'ordering': ['modified_at'], 'verbose_name': 'responsible', 'verbose_name_plural': 'responsibles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'default_related_name': 'services', 'permissions': [('can_edit_global_template', 'Can edit the service containing the global workflow templates')], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='servicecustomer',
            options={'default_related_name': 'service_customers', 'verbose_name': 'service to customer relationship', 'verbose_name_plural': 'service to customer relationships'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'default_related_name': 'shares', 'verbose_name': 'share', 'verbose_name_plural': 'shares'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'default_related_name': 'steps', 'ordering': ('index',), 'verbose_name_plural': 'steps'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name': 'tenant', 'verbose_name_plural': 'tenants'},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={'default_related_name': 'workflows', 'ordering': ('index',), 'verbose_name': 'workflow', 'verbose_name_plural': 'workflows'},
        ),
        migrations.AlterModelOptions(
            name='workinstruction',
            options={'default_related_name': 'work_instructions', 'ordering': ['modified_at'], 'verbose_name': 'work instruction', 'verbose_name_plural': 'work instructions'},
        ),
    ]
