# Generated by Django 3.1.7 on 2023-07-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0056_auto_20230625_0609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'default_related_name': 'profiles', 'ordering': ('index',), 'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
