# Generated by Django 3.1.7 on 2023-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0057_auto_20230724_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, editable=False),
        ),
    ]
