# Generated by Django 3.1.7 on 2023-07-24 21:04

from django.db import migrations


def reorder_existing_profiles(apps, schema_editor):
    Tenant = apps.get_model('workflows', 'Tenant')

    for tenant in Tenant.objects.all():
      for i, profile in enumerate(Profile.unscoped.filter(tenant_id=tenant.id)):
        profile.index = i + 1
        profile.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0058_auto_20230724_1949'),
    ]

    operations = [
        #migrations.RunPython(reorder_existing_profiles),
    ]
