# Generated by Django 3.1.7 on 2023-07-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0059_reorder_existing_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationunit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
