# Generated by Django 3.1.7 on 2023-07-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0060_auto_20230724_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
    ]
