# Generated by Django 3.1.7 on 2023-10-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0061_auto_20230725_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish')], default='fi', error_messages={'invalid_choice': 'Wrong language choice', 'required': 'You must choose the language'}, max_length=2, verbose_name='Language'),
        ),
    ]
