# Generated by Django 3.1.7 on 2023-11-13 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
        ('workflows', '0062_account_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='invitation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.invitation'),
        ),
    ]
