# Generated by Django 5.0.7 on 2024-08-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0063_account_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.step'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.activity'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='organization_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.organizationunit'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.profile'),
        ),
        migrations.AlterField(
            model_name='responsible',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='servicecustomer',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.customer'),
        ),
        migrations.AlterField(
            model_name='servicecustomer',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.service'),
        ),
        migrations.AlterField(
            model_name='servicecustomer',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='share',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='step',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='step',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='based_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.service'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AlterField(
            model_name='workinstruction',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.responsible'),
        ),
        migrations.AlterField(
            model_name='workinstruction',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
    ]
