# Generated by Django 5.0.7 on 2024-08-06 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0067_uuidtaggeditem_alter_employee_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'default_related_name': 'trainings_organized', 'verbose_name': 'training', 'verbose_name_plural': 'trainings'},
        ),
        migrations.CreateModel(
            name='TrainingAttended',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended', to='workflows.employee')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendants', to='workflows.training')),
            ],
            options={
                'verbose_name': 'training attended',
                'verbose_name_plural': 'trainings attended',
                'default_related_name': 'trainings_attended',
            },
        ),
        migrations.CreateModel(
            name='TrainingOrganized',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
                ('training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized', to='workflows.training')),
            ],
            options={
                'verbose_name': 'training organized',
                'verbose_name_plural': 'trainings organized',
                'default_related_name': 'trainings',
            },
        ),
    ]
