# Generated by Django 5.0.7 on 2024-08-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0068_alter_training_options_trainingattended_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'default_related_name': 'trainings', 'verbose_name': 'training', 'verbose_name_plural': 'trainings'},
        ),
        migrations.AlterModelOptions(
            name='trainingorganized',
            options={'default_related_name': 'trainings_organized', 'verbose_name': 'training organized', 'verbose_name_plural': 'trainings organized'},
        ),
    ]
