# Generated by Django 5.0.7 on 2024-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0069_alter_training_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='process',
            field=models.CharField(choices=[('agree', 'Agree'), ('change', 'Change'), ('recover', 'Recover'), ('operation', 'Operation'), ('risk', 'Risk')], default='recover', max_length=32),
        ),
    ]
