# Generated by Django 5.1.4 on 2025-01-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0070_alter_workflow_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingattended',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='training',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='training',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='training',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='training',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingattended',
            name='training',
        ),
        migrations.RemoveField(
            model_name='trainingorganized',
            name='training',
        ),
        migrations.RemoveField(
            model_name='trainingattended',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trainingattended',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='trainingattended',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='trainingorganized',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trainingorganized',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='trainingorganized',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
        migrations.DeleteModel(
            name='TrainingAttended',
        ),
        migrations.DeleteModel(
            name='TrainingOrganized',
        ),
    ]
