# Generated by Django 3.1.7 on 2023-10-31 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('why', models.TextField(verbose_name='Why do you want to use this service?')),
                ('source', models.TextField(verbose_name='Where did you hear about this service?')),
                ('interested_groups', models.TextField(verbose_name='Are you member of a groups that might have people interested in participating in Lovezone?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waiting list entry',
                'verbose_name_plural': 'Waiting list entries',
            },
        ),
        migrations.CreateModel(
            name='WaitingListInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.waitinglistentry')),
            ],
            options={
                'verbose_name': 'Waiting list invite',
                'verbose_name_plural': 'Waiting list invites',
            },
        ),
    ]
