# Generated by Django 3.1.7 on 2023-11-13 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('key', models.UUIDField(default=uuid.uuid4)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
