# Generated by Django 5.1.6 on 2025-02-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invitation_id_alter_waitinglistentry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglistentry',
            name='interested_groups',
            field=models.TextField(verbose_name='Are you member of a groups that might have people interested in participating in USM Tools?'),
        ),
    ]
