from django.urls import path,register_converter

from django.views.generic.base import RedirectView

from . import views

app_name = "workflows"

urlpatterns = [
    path('', RedirectView.as_view(url='/workflows/tenants/')),
    path('tenants/', views.TenantList.as_view(), name='tenant-list'),
    path('tenants/create/', views.TenantCreate.as_view(), name='tenant-create'),
    path('<uuid:pk>/update/', views.TenantUpdate.as_view(), name='tenant-update'),
    path('<uuid:pk>/delete/', views.TenantDelete.as_view(), name='tenant-delete'),
    path('<uuid:tenant_id>/export/', views.TenantExport.as_view(), name='tenant-export'),
    path('<uuid:tenant_id>/organization-units/', views.OrganizationUnitList.as_view(), name='organization-unit-list'),
    path('<uuid:tenant_id>/organization-units/<uuid:pk>/', views.OrganizationUnitDetail.as_view(), name='organization-unit-detail'),
    path('<uuid:tenant_id>/organization-units/create/', views.OrganizationUnitCreate.as_view(), name='organization-unit-create'),
    path('<uuid:tenant_id>/organization-units/<uuid:pk>/create/', views.OrganizationUnitCreate.as_view(), name='organization-unit-create-child'),
    path('<uuid:tenant_id>/organization-units/<uuid:pk>/delete/', views.OrganizationUnitDelete.as_view(), name='organization-unit-delete'),
    path('<uuid:tenant_id>/organization-units/<uuid:pk>/update/', views.OrganizationUnitUpdate.as_view(), name='organization-unit-update'),
    #path('<uuid:tenant_id>/shares/', views.ShareList.as_view(), name='share-list'),
    #path('<uuid:tenant_id>/shares/create/', views.ShareCreate.as_view(), name='share-create'),
    #path('<uuid:tenant_id>/shares/<uuid:pk>/delete/', views.ShareDelete.as_view(), name='share-delete'),
    path('<uuid:tenant_id>/services/<uuid:pk>/workflows/create/', views.RoutineCreate.as_view(), name='routine-create'),
    path('<uuid:tenant_id>/services/', views.ServiceList.as_view(), name='service-list'),
    path('<uuid:tenant_id>/services/create/', views.ServiceCreate.as_view(), name='service-create'),
    path('<uuid:tenant_id>/services/<uuid:pk>/delete/', views.ServiceDelete.as_view(), name='service-delete'),
    path('<uuid:tenant_id>/services/<uuid:pk>/update/', views.ServiceUpdate.as_view(), name='service-update'),
    path('<uuid:tenant_id>/services/<uuid:pk>/', views.ServiceDetail.as_view(), name='service-detail'),
    path('<uuid:tenant_id>/services/<uuid:pk>/customers/add/', views.ServiceCustomerAdd.as_view(), name='service-customer-add'),
    path('<uuid:tenant_id>/service-customers/<uuid:pk>/remove/', views.ServiceCustomerRemove.as_view(), name='service-customer-remove'),
    path('<uuid:tenant_id>/profiles/', views.ProfileList.as_view(), name='profile-list'),
    path('<uuid:tenant_id>/profiles/<uuid:pk>/', views.ProfileDetail.as_view(), name='profile-detail'),
    path('<uuid:tenant_id>/profiles/create/', views.ProfileCreate.as_view(), name='profile-create'),
    path('<uuid:tenant_id>/profiles/<uuid:pk>/delete/', views.ProfileDelete.as_view(), name='profile-delete'),
    path('<uuid:tenant_id>/profiles/<uuid:pk>/update/', views.ProfileUpdate.as_view(), name='profile-update'),
    path('<uuid:tenant_id>/profiles/<uuid:pk>/up/', views.ProfileUp.as_view(), name='profile-up'),
    path('<uuid:tenant_id>/profiles/<uuid:pk>/down/', views.ProfileDown.as_view(), name='profile-down'),
    path('<uuid:tenant_id>/customers/', views.CustomerList.as_view(), name='customer-list'),
    path('<uuid:tenant_id>/customers/create/', views.CustomerCreate.as_view(), name='customer-create'),
    path('<uuid:tenant_id>/customers/<uuid:pk>/delete/', views.CustomerDelete.as_view(), name='customer-delete'),
    path('<uuid:tenant_id>/customers/<uuid:pk>/update/', views.CustomerUpdate.as_view(), name='customer-update'),
    path('<uuid:tenant_id>/routines/<uuid:pk>/', views.RoutineDetail.as_view(), name='routine-detail'),
    path('<uuid:tenant_id>/routines/<uuid:pk>/delete/', views.RoutineDelete.as_view(), name='routine-delete'),
    path('<uuid:tenant_id>/routines/<uuid:pk>/update/', views.RoutineUpdate.as_view(), name='routine-update'),
    path('<uuid:tenant_id>/routines/<uuid:pk>/diagram/', views.RoutineDiagram.as_view(), name='routine-diagram'),
    path('<uuid:tenant_id>/steps/<uuid:pk>/activities/create/', views.ActivityCreate.as_view(), name='activity-create'),
    path('<uuid:tenant_id>/steps/<uuid:pk>/', views.StepDetail.as_view(), name='step-detail'),
    path('<uuid:tenant_id>/steps/<uuid:pk>/skip/', views.StepSkip.as_view(), name='step-skip'),
    path('<uuid:tenant_id>/steps/<uuid:pk>/unskip/', views.StepUnskip.as_view(), name='step-unskip'),
    path('<uuid:tenant_id>/activities/<uuid:pk>/delete/', views.ActivityDelete.as_view(), name='activity-delete'),
    path('<uuid:tenant_id>/activities/<uuid:pk>/update/', views.ActivityUpdate.as_view(), name='activity-update'),
    path('<uuid:tenant_id>/activities/<uuid:pk>/up/', views.ActivityUp.as_view(), name='activity-up'),
    path('<uuid:tenant_id>/activities/<uuid:pk>/down/', views.ActivityDown.as_view(), name='activity-down'),
    path('<uuid:tenant_id>/activities/<uuid:pk>/actions/create/', views.ActionCreateOrUpdate.as_view(), name='action-create'),
    path('<uuid:tenant_id>/activities/<uuid:pk>/skip/', views.ActivitySkip.as_view(), name='activity-skip'),
    path('<uuid:tenant_id>/activities/<uuid:pk>/unskip/', views.ActivityUnskip.as_view(), name='activity-unskip'),
    path('<uuid:tenant_id>/actions/<uuid:pk>/update/', views.ActionUpdate.as_view(), name='action-update'),
    path('<uuid:tenant_id>/actions/<uuid:pk>/delete/', views.ActionDelete.as_view(), name='action-delete'),
    path('<uuid:tenant_id>/actions/<uuid:pk>/up/', views.ActionUp.as_view(), name='action-up'),
    path('<uuid:tenant_id>/actions/<uuid:pk>/down/', views.ActionDown.as_view(), name='action-down'),
    path('<uuid:tenant_id>/responsibilities/<uuid:pk>/instructions/create/', views.InstructionCreate.as_view(), name='instruction-create'),
    path('<uuid:tenant_id>/profiles/<uuid:pk>/tasks/create/', views.TaskCreate.as_view(), name='task-create'),
    path('<uuid:tenant_id>/tasks/<uuid:pk>/', views.TaskDetail.as_view(), name='task-detail'),
    path('<uuid:tenant_id>/tasks/<uuid:pk>/update/', views.TaskUpdate.as_view(), name='task-update'),
    path('<uuid:tenant_id>/tasks/<uuid:pk>/delete/', views.TaskDelete.as_view(), name='task-delete'),
    path('<uuid:tenant_id>/instructions/<uuid:pk>/delete/', views.InstructionDelete.as_view(), name='instruction-delete'),
    path('<uuid:tenant_id>/instructions/<uuid:pk>/update/', views.InstructionUpdate.as_view(), name='instruction-update'),
    #path('<uuid:tenant_id>/user/services/', views.UserServiceList.as_view(), name='user-service-list'),
    path('<uuid:tenant_id>/routines/<uuid:pk>/printable/', views.RoutineDetailPrintable.as_view(), name='routine-detail-printable'),
    #path('<uuid:tenant_id>/shared/workflows/<uuid:pk>/<uuid:token1>/<uuid:token2>/', views.SharedRoutineDetail.as_view(), name='shared-routine-detail'),
    #path('<uuid:tenant_id>/profile/services/', views.ProfileServiceList.as_view(), name='profile-service-list'),
    #path('<uuid:tenant_id>/profile/workflows/<uuid:pk>/', views.ProfileRoutineDetail.as_view(), name='profile-routine-detail'),

]
