# Generated by Django 5.1.4 on 2024-12-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='statements',
        ),
    ]
