# Generated by Django 5.1.4 on 2025-01-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='projects',
            field=models.ManyToManyField(related_name='domains', to='projects.project'),
        ),
        migrations.AddField(
            model_name='target',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='projects.project'),
        ),
    ]
