# Generated by Django 5.1.4 on 2024-12-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
