# Generated by Django 5.1.4 on 2025-01-09 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliances', '0001_initial'),
        ('projects', '0001_initial'),
        ('workflows', '0071_remove_trainingattended_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='projects',
            field=models.ManyToManyField(related_name='domains', to='projects.project'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.domain'),
        ),
        migrations.AddField(
            model_name='category',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.domain'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='section',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.domain'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.section'),
        ),
        migrations.AddField(
            model_name='statement',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.requirement'),
        ),
        migrations.AddField(
            model_name='statement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='constraintstatement',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_statements', to='compliances.statement'),
        ),
        migrations.AddField(
            model_name='target',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='target',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='targetsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compliances.section'),
        ),
        migrations.AddField(
            model_name='targetsection',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_sections', to='compliances.target'),
        ),
        migrations.AddField(
            model_name='targetsection',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='target',
            name='sections',
            field=models.ManyToManyField(through='compliances.TargetSection', to='compliances.section'),
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='projects.project'),
        ),
        migrations.AddField(
            model_name='team',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='compliances.team'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('domain', 'parent', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('section', 'index')},
        ),
    ]
