# Generated by Django 5.1.4 on 2025-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='story_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
