# Generated by Django 5.1.4 on 2024-12-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0002_alter_constraint_text_alter_requirement_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='docid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
