# Generated by Django 5.0.7 on 2024-08-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0002_remove_requirement_visible_id_requirement_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
