# Generated by Django 5.1.4 on 2025-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
