# Generated by Django 5.1.6 on 2025-02-19 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliances', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('projects', '0002_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.category'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='constraintdefinition',
            name='constraint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.constraint'),
        ),
        migrations.AddField(
            model_name='constraintdefinition',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='constraintdependency',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compliances.constraint'),
        ),
        migrations.AddField(
            model_name='constraintdependency',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compliances.constraint'),
        ),
        migrations.AddField(
            model_name='constraintdependency',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='dependencies',
            field=models.ManyToManyField(through='compliances.ConstraintDependency', to='compliances.constraint'),
        ),
        migrations.AddField(
            model_name='constraintstatement',
            name='constraint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_statements', to='compliances.constraint'),
        ),
        migrations.AddField(
            model_name='constraintstatement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_managements', to='projects.team'),
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='definition',
            name='ref_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='definition',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='constraintdefinition',
            name='definition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.definition'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='definitions',
            field=models.ManyToManyField(through='compliances.ConstraintDefinition', to='compliances.definition'),
        ),
        migrations.AddField(
            model_name='domain',
            name='projects',
            field=models.ManyToManyField(related_name='domains', to='projects.project'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='definition',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.domain'),
        ),
        migrations.AddField(
            model_name='datamanagement',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_managements', to='compliances.domain'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.domain'),
        ),
        migrations.AddField(
            model_name='category',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.domain'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='section',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.domain'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='compliances.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.section'),
        ),
        migrations.AddField(
            model_name='statement',
            name='requirement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.requirement'),
        ),
        migrations.AddField(
            model_name='statement',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='constraintstatement',
            name='statement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constraint_statements', to='compliances.statement'),
        ),
        migrations.AddField(
            model_name='target',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='projects.project'),
        ),
        migrations.AddField(
            model_name='target',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='targetsection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compliances.section'),
        ),
        migrations.AddField(
            model_name='targetsection',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_sections', to='compliances.target'),
        ),
        migrations.AddField(
            model_name='targetsection',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='target',
            name='sections',
            field=models.ManyToManyField(through='compliances.TargetSection', to='compliances.section'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('domain', 'parent', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('section', 'index')},
        ),
    ]
