# Generated by Django 5.1.4 on 2025-01-09 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0002_initial'),
        ('projects', '0002_remove_projectteam_compliance_team_projectteam_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='projects.projectteam'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
