# Generated by Django 5.1.6 on 2025-02-12 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0003_constraint_key'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='ref_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='definition',
            name='ref_entity_type',
            field=models.CharField(choices=[('not-defined', 'Not defined'), ('document', 'Document'), ('task', 'Task'), ('routine', 'Routine'), ('profile', 'Profile')], default='not-defined', max_length=32),
        ),
        migrations.AddField(
            model_name='definition',
            name='ref_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
