# Generated by Django 5.1.6 on 2025-02-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='ref_entity_type',
            field=models.CharField(choices=[('not-defined', 'Not defined'), ('document', 'Document'), ('task', 'Task'), ('risk', 'Risk'), ('routine', 'Routine'), ('profile', 'Profile')], default='not-defined', max_length=32),
        ),
    ]
