# Generated by Django 5.1.6 on 2025-02-23 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0003_initial'),
        ('projects', '0002_initial'),
        ('workflows', '0002_profile_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataManagement',
            new_name='DataManagementPlan',
        ),
    ]
