# Generated by Django 5.1.4 on 2025-01-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamanagement',
            name='allow_modification',
            field=models.BooleanField(default=True),
        ),
    ]
