# Generated by Django 5.0.7 on 2024-08-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0003_domain_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
