# Generated by Django 5.1.6 on 2025-02-13 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0004_definition_ref_content_type_and_more'),
        ('workflows', '0006_trigram_ext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compliances.constraint')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='compliances.constraint')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='constraint',
            name='dependencies',
            field=models.ManyToManyField(through='compliances.ConstraintDependency', to='compliances.constraint'),
        ),
    ]
