# Generated by Django 5.1.6 on 2025-02-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0004_datamanagementplan_delete_datamanagement'),
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamanagementplan',
            name='allow_policy_change',
        ),
        migrations.RemoveField(
            model_name='datamanagementplan',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='datamanagementplan',
            name='policy',
        ),
        migrations.AddField(
            model_name='datamanagementplan',
            name='plan',
            field=models.CharField(choices=[('not-defined', 'Not defined'), ('keep', 'Keep the existing status'), ('implement', 'Implement in this project'), ('another-project', 'Implemented in another project'), ('postpone', 'Postpone integration')], default='not-defined', max_length=32),
        ),
        migrations.AlterField(
            model_name='datamanagementplan',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_management_plans', to='compliances.domain'),
        ),
        migrations.AlterField(
            model_name='datamanagementplan',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_managements', to='projects.team', verbose_name='Team responsible for this data type'),
        ),
    ]
