# Generated by Django 5.0.7 on 2024-08-04 13:00

import workflows.tenant_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0004_constraint_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=workflows.tenant_models.get_next_index, editable=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=workflows.tenant_models.get_next_index, editable=False),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=workflows.tenant_models.get_next_index, editable=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=workflows.tenant_models.get_next_index, editable=False),
        ),
    ]
