# Generated by Django 5.1.4 on 2025-01-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0004_datamanagement_allow_modification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamanagement',
            old_name='allow_modification',
            new_name='allow_policy_change',
        ),
    ]
