# Generated by Django 5.1.6 on 2025-02-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0005_definition_ref_plural_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='term_plural',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
