# Generated by Django 5.1.6 on 2025-02-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0005_remove_datamanagementplan_allow_policy_change_and_more'),
        ('mir', '0003_datamanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamanagementplan',
            name='data_management',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mir.datamanagement'),
        ),
    ]
