# Generated by Django 5.1.4 on 2025-01-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0005_rename_allow_modification_datamanagement_allow_policy_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
