# Generated by Django 5.1.6 on 2025-02-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0005_constraintdependency_constraint_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.domain'),
        ),
    ]
