# Generated by Django 5.0.7 on 2024-08-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0005_alter_constraint_index_alter_domain_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('implemented', 'Implemented'), ('failed', 'Failed'), ('non-compliant', 'Non-compliant'), ('compliant', 'Compliant'), ('audited', 'Audited')], default='new', max_length=32),
        ),
    ]
