# Generated by Django 5.1.4 on 2025-01-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0006_requirement_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
