# Generated by Django 5.1.6 on 2025-02-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0006_definition_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='ref_plural',
            field=models.BooleanField(default=False),
        ),
    ]
