# Generated by Django 5.1.6 on 2025-02-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0006_datamanagementplan_data_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
