# Generated by Django 5.1.6 on 2025-02-14 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0007_definition_ref_plural'),
        ('workflows', '0006_trigram_ext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(db_index=True, editable=False)),
                ('constraint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.constraint')),
                ('definition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compliances.definition')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AddField(
            model_name='constraint',
            name='definitions',
            field=models.ManyToManyField(through='compliances.ConstraintDefinition', to='compliances.definition'),
        ),
    ]
