# Generated by Django 5.1.6 on 2025-02-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0007_alter_section_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='statements',
            field=models.ManyToManyField(related_name='constraints', through='compliances.ConstraintStatement', to='compliances.statement'),
        ),
        migrations.AddField(
            model_name='constraint',
            name='xref_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('verified', 'Verified')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='domain',
            name='xref_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('verified', 'Verified')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='requirement',
            name='xref_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('verified', 'Verified')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='section',
            name='xref_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('verified', 'Verified')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='statement',
            name='xref_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('verified', 'Verified')], default='draft', max_length=32),
        ),
    ]
