# Generated by Django 5.1.4 on 2025-01-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0007_constraint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='is_generic',
            field=models.BooleanField(default=True, help_text='If True statement, only this needs to be done only once. If False, needs to be implemented seperately for each target in scope.'),
        ),
        migrations.AddField(
            model_name='statement',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
