# Generated by Django 5.1.4 on 2024-12-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0007_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('implemented', 'Implemented'), ('failed', 'Failed'), ('non-compliant', 'Non-compliant'), ('compliant', 'Compliant'), ('audited', 'Audited')], default='new', max_length=32),
        ),
    ]
