# Generated by Django 5.1.4 on 2025-01-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0008_constraint_is_generic_statement_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='description',
            new_name='text',
        ),
    ]
