# Generated by Django 5.1.4 on 2024-12-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0008_alter_constraint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='constraint',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='section',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='section',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='term',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='term',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='term',
            name='modified_at',
        ),
        migrations.RemoveField(
            model_name='term',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='constraint',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='term',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, editable=False),
        ),
    ]
