# Generated by Django 5.1.6 on 2025-02-17 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliances', '0008_constraintdefinition_constraint_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='compliances.section'),
        ),
    ]
