# Generated by Django 3.1.7 on 2024-01-15 22:40

from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USMSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control_of_planning', models.PositiveIntegerField(choices=[(1, 'poorly'), (2, 'quite poorly'), (3, 'somewhat poorly'), (4, 'ok'), (5, 'somewhat well'), (6, 'quite well'), (7, 'well')], verbose_name='My organization is in control of our planning and our resources for the delivery of our services')),
                ('supplier_relationship_problems', models.PositiveIntegerField(choices=[(1, 'very often'), (2, 'often'), (3, 'somewhat often'), (4, 'somwhat rarely'), (5, 'quite rarely'), (6, 'rarely'), (7, 'never')], verbose_name='My organization encounters problems with our supplier relationships, impacting our product/service quality')),
                ('reporting_service_quality', models.PositiveIntegerField(choices=[(1, 'bad'), (2, 'quite bad'), (3, 'somewhat bad'), (4, 'ok'), (5, 'pretty good'), (6, 'quite good'), (7, 'very good')], verbose_name='The reporting of service quality in my organization is')),
                ('employee_opinion', models.PositiveIntegerField(choices=[(1, 'very poor'), (2, 'quite poor'), (3, 'somewhat poor'), (4, 'ok'), (5, 'pretty good'), (6, 'quite good'), (7, 'very good')], verbose_name='The employees of my organization consider the organization of the work to be')),
                ('proactive_improvements', models.PositiveIntegerField(choices=[(1, 'never'), (2, 'almost never'), (3, 'rarely'), (4, 'sometimes'), (5, 'often'), (6, 'almost always'), (7, 'always')], verbose_name='My organization manages improvements in a proactive way')),
                ('unclear_roles', models.PositiveIntegerField(choices=[(1, 'never'), (2, 'rarely'), (3, 'quite rarely'), (4, 'somwhat often'), (5, 'quite often'), (6, 'often'), (7, 'always')], verbose_name='In my organization, issues arise from unclear roles and responsibilities, or ownership')),
                ('customer_requests_ok', models.PositiveIntegerField(choices=[(1, 'never'), (2, 'rarely'), (3, 'quite rarely'), (4, 'somwhat often'), (5, 'quite often'), (6, 'often'), (7, 'always')], verbose_name='My organization solves most of the customer requests as agreed')),
                ('practices_documented', models.PositiveIntegerField(choices=[(1, 'no processes'), (2, 'few processes'), (3, 'some processes'), (4, 'many processes'), (5, 'most processes'), (6, 'almost all processes'), (7, 'all processes')], verbose_name="My organization's processes and practices are documented")),
                ('standard_problems', models.PositiveIntegerField(choices=[(1, 'very many difficulties'), (2, 'many difficulties'), (3, 'moderate difficulties'), (4, 'some difficulties'), (5, 'few difficulties'), (6, 'very few difficulties'), (7, 'no difficulties')], verbose_name='My organization has difficulties to comply with one ore more necessary industry standards (ISO 9k, ISO 27k, ISO 13k etc.)')),
                ('adequate_tooling', models.PositiveIntegerField(choices=[(1, 'no processes'), (2, 'few processes'), (3, 'some processes'), (4, 'many processes'), (5, 'most processes'), (6, 'almost all processes'), (7, 'all processes')], verbose_name="My organization's processes and practices are automated with adequate tooling where possible")),
                ('services_and_agreements_clearly_specified', models.PositiveIntegerField(choices=[(1, 'none'), (2, 'few'), (3, 'some'), (4, 'many'), (5, 'most'), (6, 'almost all'), (7, 'all')], verbose_name='All our services and related agreements are clearly specified')),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True, verbose_name='Your preferred countries')),
                ('lang', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], max_length=2, verbose_name='Preferred language')),
                ('industry', models.CharField(choices=[('agriculture-forestry-mining', 'Agriculture, Forestry, Mining'), ('industrials', 'Industrials (Manufacturing, Construction, etc.)'), ('energy-utilities', 'Energy, Utilities'), ('transport-logistics', 'Transport, Logistics'), ('media-creative', 'Media, Creative Industries'), ('it-data-infra-telecom', 'Information Technology, Data Infrastructure, Telecom'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('life-sciences', 'Life Sciences'), ('retail-ecommerce', 'Retail, E-Commerce'), ('hospitality-food-leisure-travel', 'Hospitality, Food, Leisure Travel'), ('public-social-service', 'Public Service, Social Service'), ('financial-services', 'Financial Services'), ('professional-services', 'Professional Services (Law, Consulting, etc.)'), ('other', 'Other')], max_length=32, verbose_name='Industry of your organisation')),
                ('size', models.CharField(choices=[('1', '1'), ('2-5', '2-5'), ('6-10', '6-10'), ('11-50', '11-50'), ('51-100', '51-100'), ('101-500', '101-500'), ('501-1000', '501-1000'), ('1001-5000', '1001-5000'), ('5000-', '5000-')], max_length=32, verbose_name='Size of your organisation')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('report_ok', models.BooleanField(blank=True, default=False, verbose_name='I want to get a report by email')),
                ('sales_ok', models.BooleanField(blank=True, default=False, verbose_name='I can be contacted by USM professionals to go over my needs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
