# Generated by Django 3.1.7 on 2024-03-19 12:11

from django.db import migrations, models
import django_countries.fields
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('low', models.PositiveSmallIntegerField(verbose_name='Lowest option that matches')),
                ('high', models.PositiveSmallIntegerField(verbose_name='Highest option that matches')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Text (en)')),
            ],
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='adequate_tooling',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='control_of_planning',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='customer_requests_ok',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='employee_opinion',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='practices_documented',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='proactive_improvements',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='reporting_service_quality',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='services_and_agreements_clearly_specified',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='standard_problems',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='supplier_relationship_problems',
        ),
        migrations.RemoveField(
            model_name='usmsurvey',
            name='unclear_roles',
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='compliance',
            field=survey.models.Question(choices=[(1, 'Always'), (2, 'Usually'), (3, 'Often'), (4, 'Neutral'), (5, 'Sometimes'), (6, 'Rarely'), (7, 'Never')], default=0, help_text='We have difficulties to comply with one or more required industry standards (ISO 9k, ISO 27k, ISO 13k etc.)', verbose_name='Standard compliance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='documentation',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=0, help_text='The ways we work (our daily routines) are adequately documented', verbose_name='Documentation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='employee',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='Our employees are satisfied with the way we organize our work', verbose_name='Employees'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='glossary',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='We have a formalized and shared business glossary (definitions of terms) and it is actively used throughout the organization', verbose_name='Glossary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='internal_reporting',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='The reporting of service quality in my organization is good', verbose_name='Internal reporting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='planning',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='We are in control of our planning and our resources for the delivery of our services', verbose_name='Planning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='proactive',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='We manage improvements in a proactive way', verbose_name='Proactive improvements'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='reporting',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='Our service reporting fully supports the expectations of our customers', verbose_name='Customer reporting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='request',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='We solve most of the customer requests as agreed', verbose_name='Customer requests'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='responsibilities',
            field=survey.models.Question(choices=[(1, 'Always'), (2, 'Usually'), (3, 'Often'), (4, 'Neutral'), (5, 'Sometimes'), (6, 'Rarely'), (7, 'Never')], default=1, help_text='We have issues arising from unclear roles and responsibilities, or ownership', verbose_name='Roles and responsibilities'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='services',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='Our services and related agreements are clearly specified', verbose_name='Services and agreement specification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='supplier',
            field=survey.models.Question(choices=[(1, 'Always'), (2, 'Usually'), (3, 'Often'), (4, 'Neutral'), (5, 'Sometimes'), (6, 'Rarely'), (7, 'Never')], default=1, help_text='We encounter problems with our supplier relationships, impacting our product/service quality', verbose_name='Suppliers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usmsurvey',
            name='tooling',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], default=1, help_text='The ways we work (our daily routines) are automated with adequate tooling where possible', verbose_name='Tooling'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usmsurvey',
            name='countries',
            field=django_countries.fields.CountryField(max_length=746, multiple=True, verbose_name='The countries where your organization operates'),
        ),
        migrations.AlterField(
            model_name='usmsurvey',
            name='lang',
            field=models.CharField(choices=[('nl', 'Dutch'), ('en', 'English'), ('fi', 'Finnish'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish')], max_length=2, verbose_name='Your preferred language'),
        ),
        migrations.AlterField(
            model_name='usmsurvey',
            name='sales_ok',
            field=models.BooleanField(blank=True, default=False, verbose_name='USM professionals may contact me so we can go over our needs'),
        ),
    ]
