# Generated by Django 3.1.7 on 2024-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20240319_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('low', models.PositiveSmallIntegerField(verbose_name='Lowest option that matches')),
                ('high', models.PositiveSmallIntegerField(verbose_name='Highest option that matches')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Text (en)')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
