# Generated by Django 3.1.7 on 2024-03-19 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20240319_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foo',
            new_name='Answer',
        ),
    ]
