# Generated by Django 3.1.7 on 2024-03-20 05:16

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20240319_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='usmsurvey',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Organisation name'),
        ),
        migrations.AlterField(
            model_name='usmsurvey',
            name='services',
            field=survey.models.Question(choices=[(1, 'Never'), (2, 'Rarely'), (3, 'Sometimes'), (4, 'Neutral'), (5, 'Often'), (6, 'Usually'), (7, 'Always')], help_text='Our services and related agreements are clearly specified', verbose_name='Service and agreement specification'),
        ),
    ]
