# Generated by Django 3.1.7 on 2024-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20240320_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('organization', models.CharField(max_length=255, verbose_name='Orgnization name')),
                ('title', models.CharField(max_length=255, verbose_name='Your title')),
                ('rationale', models.TextField(blank=True, null=True, verbose_name='Why do you wish to participate in the survey?')),
            ],
        ),
    ]
