# Generated by Django 3.1.7 on 2024-04-22 20:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_qualify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('organization', models.CharField(max_length=255, verbose_name='Orgnization name')),
                ('title', models.CharField(max_length=255, verbose_name='Your title')),
                ('rationale', models.TextField(blank=True, null=True, verbose_name='Why do you wish to participate in the survey?')),
                ('category', models.CharField(choices=[('c-level', 'C-level'), ('itsm-pro', 'ITSM pro'), ('other', 'Other'), ('rejected', 'Rejected')], max_length=32, verbose_name='Category')),
                ('status', models.CharField(choices=[('unqualified', 'Unqualified'), ('rejected', 'Rejected'), ('free', 'Free'), ('claimed', 'Claimed')], max_length=32, verbose_name='Status')),
            ],
        ),
        migrations.DeleteModel(
            name='Qualify',
        ),
    ]
