# Generated by Django 5.1.6 on 2025-02-19 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('', 'Let us know your industry'), ('agriculture-forestry-mining', 'Agriculture, Forestry, Mining'), ('industrials', 'Industrials (Manufacturing, Construction, etc.)'), ('energy-utilities', 'Energy, Utilities'), ('transport-logistics', 'Transport, Logistics'), ('media-creative', 'Media, Creative Industries'), ('it-data-infra-telecom', 'Information Technology, Data Infrastructure, Telecom'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('life-sciences', 'Life Sciences'), ('retail-ecommerce', 'Retail, E-Commerce'), ('hospitality-food-leisure-travel', 'Hospitality, Food, Leisure Travel'), ('public-social-service', 'Public Service, Social Service'), ('financial-services', 'Financial Services'), ('professional-services', 'Professional Services (Law, Consulting, etc.)'), ('other', 'Other')], max_length=32, verbose_name='Industry')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('mailing_list', models.BooleanField(blank=True, default=False)),
                ('sales_contact', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usm_simple_download_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('usm_simple_requested', models.BooleanField(default=False)),
                ('usm_simple_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
