# Generated by Django 3.1.5 on 2021-01-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(choices=[('agriculture-forestry-mining', 'Agriculture, Forestry, Mining'), ('industrials', 'Industrials (Manufacturing, Construction, etc.)'), ('energy-utilities', 'Energy, Utilities'), ('transport-logistics', 'Transport, Logistics'), ('media-creative', 'Media, Creative Industries'), ('it-data-infra-telecom', 'Information Technology, Data Infrastructure, Telecom'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('life-sciences', 'Life Sciences'), ('retail-ecommerce', 'Retail / E-Commerce'), ('hospitality-food-leisure-travel', 'Hospitality, Food, Leisure Travel'), ('public-and-social-service', 'Public Service, Social Service'), ('financial-services', 'Financial Services'), ('professional-services', 'Professional Services (Law, Consulting, etc.)'), ('other', 'Other')], default='other', max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('serves_hot_dogs', models.BooleanField(default=False)),
                ('mailing_list', models.BooleanField(default=False, help_text='Keep me updated on all of your exciting new developments!')),
                ('sales_contact', models.BooleanField(default=False, help_text='>We desperately need to fix our service management! Lets get in touch ASAP!')),
            ],
        ),
    ]
