# Generated by Django 3.1.5 on 2021-01-23 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='serves_hot_dogs',
        ),
        migrations.AlterField(
            model_name='contact',
            name='sales_contact',
            field=models.BooleanField(default=False, help_text='We desperately need to fix our service management! Lets get in touch ASAP!'),
        ),
    ]
