# Generated by Django 3.1.5 on 2021-01-24 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_auto_20210123_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='usm_simple_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='usm_simple_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
