# Generated by Django 3.1.5 on 2021-01-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_auto_20210124_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='industry',
            field=models.CharField(choices=[('', 'Let us know your industry'), ('agriculture-forestry-mining', 'Agriculture, Forestry, Mining'), ('industrials', 'Industrials (Manufacturing, Construction, etc.)'), ('energy-utilities', 'Energy, Utilities'), ('transport-logistics', 'Transport, Logistics'), ('media-creative', 'Media, Creative Industries'), ('it-data-infra-telecom', 'Information Technology, Data Infrastructure, Telecom'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('life-sciences', 'Life Sciences'), ('retail-ecommerce', 'Retail, E-Commerce'), ('hospitality-food-leisure-travel', 'Hospitality, Food, Leisure Travel'), ('public-social-service', 'Public Service, Social Service'), ('financial-services', 'Financial Services'), ('professional-services', 'Professional Services (Law, Consulting, etc.)'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_list',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sales_contact',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
