# Generated by Django 3.1.5 on 2021-01-31 03:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_auto_20210126_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='usm_simple_download_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
