# Generated by Django 3.1.6 on 2021-02-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_contact_usm_simple_download_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='industry',
            field=models.CharField(choices=[('', 'Let us know your industry'), ('agriculture-forestry-mining', 'Agriculture, Forestry, Mining'), ('industrials', 'Industrials (Manufacturing, Construction, etc.)'), ('energy-utilities', 'Energy, Utilities'), ('transport-logistics', 'Transport, Logistics'), ('media-creative', 'Media, Creative Industries'), ('it-data-infra-telecom', 'Information Technology, Data Infrastructure, Telecom'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('life-sciences', 'Life Sciences'), ('retail-ecommerce', 'Retail, E-Commerce'), ('hospitality-food-leisure-travel', 'Hospitality, Food, Leisure Travel'), ('public-social-service', 'Public Service, Social Service'), ('financial-services', 'Financial Services'), ('professional-services', 'Professional Services (Law, Consulting, etc.)'), ('other', 'Other')], max_length=32, verbose_name='Industry'),
        ),
    ]
