# Generated by Django 5.1.3 on 2024-12-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_alter_list_order_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.TextField(verbose_name='Label'),
        ),
    ]
