# Generated by Django 5.1.4 on 2024-12-11 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_task_description_alter_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
