# Generated by Django 5.1.4 on 2024-12-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_board_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
