# Generated by Django 5.1.4 on 2024-12-21 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_list_content_type_list_object_id_list_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='board',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('roadmap', 'Roadmap'), ('current', 'Current')], default='roadmap', max_length=32),
        ),
    ]
