# Generated by Django 5.1.4 on 2024-12-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_board_content_type_board_object_id_board_type'),
        ('workflows', '0070_alter_workflow_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['index']},
        ),
        migrations.RenameField(
            model_name='list',
            old_name='order',
            new_name='index',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='index',
        ),
        migrations.AddField(
            model_name='board',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='list',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant'),
        ),
    ]
