# Generated by Django 5.1.4 on 2024-12-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_alter_list_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='list_entity_name',
            field=models.CharField(default='list', max_length=255, verbose_name='List entity name'),
        ),
        migrations.AddField(
            model_name='board',
            name='max_columns',
            field=models.SmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='board',
            name='task_entity_name',
            field=models.CharField(default='task', max_length=255, verbose_name='Task entity name'),
        ),
    ]
