# Generated by Django 5.1.4 on 2024-12-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_board_list_entity_name_board_max_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='show_list_count',
            field=models.BooleanField(default=True),
        ),
    ]
