# Generated by Django 5.1.6 on 2025-02-21 07:10

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mir', '0002_risk'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='mir.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
