# Generated by Django 5.1.6 on 2025-02-23 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mir', '0002_initial'),
        ('workflows', '0002_profile_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveSmallIntegerField(db_index=True, default=0, editable=False)),
                ('allow_policy_change', models.BooleanField(default=True)),
                ('policy', models.CharField(choices=[('not-defined', 'Not defined'), ('manual', 'Manual'), ('linked', 'Link'), ('replicated', 'Replicated'), ('managed', 'Managed')], default='not-defined', max_length=32)),
                ('status', models.CharField(choices=[('not-defined', 'Not defined'), ('prototyping', 'Prototyping'), ('deveopment', 'Development'), ('testing', 'Testing'), ('production', 'Production')], default='not-defined', max_length=32)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.tenant')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
