# Generated by Django 5.1.6 on 2025-02-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mir', '0003_datamanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamanagement',
            name='status',
            field=models.CharField(choices=[('not-defined', 'Not defined'), ('prototyping', 'Prototyping'), ('development', 'Development'), ('testing', 'Testing'), ('production', 'Production')], default='not-defined', max_length=32),
        ),
    ]
